title: "l'Hexagone"
author: Saturn
remote_theme: cotes2020/jekyll-theme-chirpy
plugins:
  - jekyll-remote-theme
theme_mode: dark
github:
  username: satindra-r
social:
  name: Saturn
  email: satinda.r@gmail.com
  links:
    - https://github.com/satindra-r